# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
 workflow_dispatch:

jobs:
  buildlnx:
    name: Build linux
    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run make
    - name: Get dpkg
      run: sudo apt-get install dpkg
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: compiled
        path: out/*
        
  buildmac:
    name: Build Mac
    runs-on: macos-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: compiled
        path: out/*
        
  buildwin:
    name: Build windows
    runs-on: windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: compiled
        path: out/*
